version: '3'

services:
  user_api:
    build: ./user_api
    ports:
      - "8001:8001"
    restart: always

  bet_api:
    build: ./bet_api
    ports:
      - "8002:8002"
    restart: always

  logs_api:
    build: ./logs_api
    ports:
      - "8003:8003"
    restart: always

  orquestador:
    build: ./orquestador
    ports:
      - "8004:8084"
    depends_on:
      - user_api
      - bet_api
      - logs_api
    restart: always
