version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: GNUpluscasino
      POSTGRES_DB: casino_db
    ports:
      - "8000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - casino_network

  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: casino_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "8001:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - casino_network

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "8002:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - casino_network

networks:
  casino_network:
    driver: bridge

volumes:
  postgres_data:
  mysql_data:
  mongo_data:

