definitions:
  main.Apuesta:
    properties:
      fecha:
        type: string
      id:
        type: integer
      juego_id:
        type: integer
      monto:
        type: number
      resultado:
        type: string
      usuario_id:
        type: integer
    type: object
  main.Juego:
    properties:
      id:
        type: integer
      nombre:
        type: string
      tipo:
        type: string
    type: object
info:
  contact: {}
paths:
  /apuestas:
    get:
      description: Obtiene todas las apuestas realizadas en el casino
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Apuesta'
            type: array
      summary: Listar apuestas
    post:
      consumes:
      - application/json
      description: Registra una nueva apuesta en el sistema
      parameters:
      - description: Datos de la apuesta a registrar
        in: body
        name: apuesta
        required: true
        schema:
          $ref: '#/definitions/main.Apuesta'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.Apuesta'
        "400":
          description: Error al procesar la solicitud
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Crear una apuesta
  /juegos:
    get:
      description: Obtiene todos los juegos disponibles en el casino
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Juego'
            type: array
      summary: Listar juegos
    post:
      consumes:
      - application/json
      description: Crea un nuevo juego en el casino
      parameters:
      - description: Datos del juego
        in: body
        name: juego
        required: true
        schema:
          $ref: '#/definitions/main.Juego'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.Juego'
        "400":
          description: Error al procesar la solicitud
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Crear un juego
  /juegos/{id}:
    delete:
      description: Elimina un juego por su ID
      parameters:
      - description: ID del juego a eliminar
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: El juego ha sido eliminado
        "404":
          description: Juego no encontrado
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Eliminar un juego
swagger: "2.0"
